### PR TITLE
Monit 29244 5 6 7

### PR DESCRIPTION
**Pull request by madhukavali123**
Fixes the vulnerabilities found from the most recent code scan Monit 29244, Monit 29245, Monit 29246, Monit 29247

### CODE REVIEW

**Review by locke-chappel — APPROVED** [review]
The changes are in-line with what I would expect. Security scan shows no remaining vulnerabilities thus addressing the related Jira items.

What I can't speak to is any potential functional impact. Standard release testing should be performed to ensure any behavioral changes in the newer library versions don't affect our intended use cases.

**Review by locke-chappel — APPROVED** [review]
I don't see any changes since my previous approval...same comments as before still apply (looks good from the security side - normal release testing should be done as per usual to ensure there aren't any subtle unexpected behavior changes due dependency changes).

**Comment by wdowling** [comment]
I'll test this change and merge once I can confirm nothing is broken.

**Comment by wdowling** [comment]
Validated this works.

**Pull request merged**
